// This file is generated by Firebase Studio.
"use server";
/**
 * @fileOverview An AI agent that suggests improvements to a user's symptom description.
 *
 * - improveSymptomDescription - A function that handles the symptom description improvement process.
 * - ImproveSymptomDescriptionInput - The input type for the improveSymptomDescription function.
 * - ImproveSymptomDescriptionOutput - The return type for the improveSymptomDescription function.
 */

import { ai } from "@/ai/genkit";
import { z } from "genkit";

const ImproveSymptomDescriptionInputSchema = z.object({
  symptomDescription: z
    .string()
    .describe("The user-provided description of their symptoms."),
});
export type ImproveSymptomDescriptionInput = z.infer<
  typeof ImproveSymptomDescriptionInputSchema
>;

const ImproveSymptomDescriptionOutputSchema = z.object({
  improvedDescription: z
    .string()
    .describe(
      "An improved version of the symptom description, with suggestions for clarity and detail."
    ),
});
export type ImproveSymptomDescriptionOutput = z.infer<
  typeof ImproveSymptomDescriptionOutputSchema
>;

export async function improveSymptomDescription(
  input: ImproveSymptomDescriptionInput
): Promise<ImproveSymptomDescriptionOutput> {
  return improveSymptomDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: "improveSymptomDescriptionPrompt",
  input: { schema: ImproveSymptomDescriptionInputSchema },
  output: { schema: ImproveSymptomDescriptionOutputSchema },
  prompt: `You are a medical expert helping users describe their symptoms more effectively.

  Please review the following symptom description and provide an improved version that is more clear, detailed, and helpful for diagnosis.

  Original Description: {{{symptomDescription}}}

  Improved Description:`,
});

const improveSymptomDescriptionFlow = ai.defineFlow(
  {
    name: "improveSymptomDescriptionFlow",
    inputSchema: ImproveSymptomDescriptionInputSchema,
    outputSchema: ImproveSymptomDescriptionOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    return output!;
  }
);
